quarkus.application.name=remote.agent
quarkus.application.version=1.0.0

quarkus.http.host=192.168.88.2
quarkus.http.port=6001
quarkus.http.cors.origins=192.168.88.2

quarkus.rest-client.skey-account.connect-timeout=5000
quarkus.rest-client.skey-account.scope=ApplicationScoped
quarkus.rest-client.skey-account.logging.body-limit=100